#! /usr/bin/python2

import os

# delcarations

junk = ["[", "]", "-", "_", "brrip", "dvdrip", "x264", "bdrip", "aac", "etrg", "hdtv", "xvid", "bluray"]
cwd = os.getcwd()

def removeDotFiles():
    """walk directory tree, delete files with filenaming that beings with "." """

    for root, dirs, files in os.walk(".", topdown=False):
        for name in files:
            if name[0] == ".":
                print("removing: " + os.path.join(root, name))
                os.remove(os.path.join(root, name))

def cleanThatUp(filename):

    print "\n", "*"*35

    tempname = filename.split('.')

    if len(tempname) > 1:
        extension = tempname.pop()

        temptempname = ' '.join(tempname)

        filetuple = (temptempname, extension)

        print "filename = ", filename
        print "filetuple = ", filetuple

    else:
        filetuple = (filename, "Null")

        print "filename = ", filename
        print "This file doesn't seem to have an extension."
        print "filetuple = ", filetuple

    lowername = filetuple[0].lower()

    for j in junk:
        if j in lowername:
            lowername = lowername.replace(j, ' ')

            print "[ FOUND %s ]" % j, 

        else:
            print "[ %s ]" % j,

    while '  ' in lowername:
        lowername = lowername.replace('  ', ' ')
        print "squashing white space...",

# and now to rename

    if filetuple[1] == "Null":
        newname = lowername
        print "\n\n--->\t", os.path.join(root, filename) 
        print "--->\t", os.path.join(root, newname)
        os.rename(os.path.join(root, filename), os.path.join(root, newname))

    else:
        newname = lowername + "." + filetuple[1]
        print "\n\n>\t", os.path.join(root, filename)
        print ">\t", os.path.join(root, newname)
        os.rename(os.path.join(root, filename), os.path.join(root, newname))


# ok go runtime.
    
removeDotFiles()

for root, dirs, files in os.walk(".", topdown=False):

    for filename in dirs:
        cleanThatUp(filename)

    for filename in files:
        cleanThatUp(filename)




            
